### ISSUE TITLE
Комментарии к заявке

### ISSUE THREAD

**Issue by aakuptsov** [Dimakl/Inflate-My-Mind#6]
1. >>Я договорился с учителем информатики из прошлой школы о том, что это приложение будет использоваться на уроках информатики в школе №1158.

Не отрицая важность этой договорённости (я не иронизирую), не совсем понятно, что это утверждение делает в проблемном поле. 

2. >>  многие школьники не имеют возможности присутствовать на уроках информатики

Тоже неясно, что имеется в виду: у них нет информатики, хотя должна быть? Нет учителей?

3. >>логические схемы

А что имеется в виду под темой "логические схемы"? Именно под темой.

4. >>Передача результатов решения схем учителю

В каком виде? Решение будет экспортироваться? В каком формате?

**Comment by Dimakl** [comment]
@aakuptsov cпасибо за коментарий! :) Действительно многое недописал в заявке.
1.
 > Я договорился с учителем информатики - не совсем понятно, что это утверждение делает в проблемном поле

Я хотел написать о том что у меня есть таковая договоренность, но перепутал и написал в неправильном месте. Оставлю только в поле заказчика.
2. 
> многие школьники не имеют возможности присутствовать на уроках информатики - неясно, что имеется в виду: у них нет информатики, хотя должна быть? Нет учителей? 

Это и правда лишее предложение. Уберу
3.
> А что имеется в виду под темой "логические схемы"?

Поменяю название темы на "булева алгебра"

4.
> В каком виде? Решение будет экспортироваться? В каком формате?

Будет передаваться информация непоредственно о том, была ли решена схема верно. А сама схема будет передаваться в приложение 2 вариантами: либо генерироваться случайно, либо же передаваться как обычное логическое выражение, к примеру `A&(B|C)=1`, где оно будет парситься и передаваться в приложение. У меня уже есть приложение под андройд, написанное мною 2 года назад, в котором я реализовал меньший функционал, но для наглядности того как примерно будут выглядеть схемы прикладываю скриншоты:
![image](https://user-images.githubusercontent.com/18268334/49885674-ea7d9800-fe48-11e8-9c79-445186b1d589.png)

![image](https://user-images.githubusercontent.com/18268334/49885796-36304180-fe49-11e8-818b-9bcd8a0a0db6.png)

Прошу написать, если у вас остались еще какие-либо вопросы по моей заявке, и достаточны ли предложеные мною здесь правки.
Благодарю за ваше время. :)

**Comment by aakuptsov** [comment]
1. >>либо же передаваться как обычное логическое выражение

Здесь нужно сделать экспорт из файла, например, через Гугл Драйв. Проблема в том, что набирать вручную длинные логические выражения с экранной клавиатуры - это неудобно, а так приложение выиграет в юзабилити.

2. Правильно ли я понимаю, что приложение генерирует рандомное булевое выражение, нужно построить его логическую схему, а потом приложение сравнивает таблицу истинности этого выражения с таблицей истинности, которую выдаёт на выходе построенная схема?

3. Какие будут изначальные логические элементы? AND, OR, NOT, что-то ещё? Будут ли, например, мультиплексоры и демультиплексоры, или их нужно реализовывать самостоятельно из других чипов?

**Comment by Dimakl** [comment]
1. > Проблема в том, что набирать вручную длинные логические выражения с экранной клавиатуры - это неудобно

Этого делать и не придется - ведь я собираюсь переписать приложение под веб :) Потому как не у всех телефон под Android, а приложение нужно сделать таким, чтобы его было проще всего использовать на уроке. Соответственно у учителя будет свой собственный, отличный от интерфейса учеников, интерфейс (извиняюсь за тавтологию) для загрузки формул на сервер.

2. > Приложение генерирует рандомное булевое выражение, нужно построить его логическую схему

Нет, видимо я не сильно понятно описал работу приложения, извиняюсь. По выражению, переданному учителем строится схема, она сама уже известна, как и число на выходе и нужно найти такие входные данные, что при подстановке в схему, она станет правильной.

![image](https://user-images.githubusercontent.com/18268334/49961440-b88d3400-ff23-11e8-9c9f-d537897a5a0a.png)

На этом скриншоте видно, что слева есть переключатели - они и меняют входные данные с 0 на 1.


3. > Будут ли, например, мультиплексоры и демультиплексоры

Я вообще забыл о них :) Но нужно реализовать, спасибо что напомнили.

**Comment by aakuptsov** [comment]
1. Тебе надо обязательно offline обсудить заявку с Данилом Ренатовичем Салимовым. Уверен, он много подскажет.

2. [https://www.coursera.org/learn/build-a-computer](url)
Если не знаешь, что это - очень советую прочитать и погрузиться. Это как раз по этой теме :)
